minetest.register_node("basic:water_source", {
  description = basic.S("Water Source"),
  drawtype = "liquid",
  waving = 3,
  tiles = {
    {
      name = "basic_water_source_animated.png",
      backface_culling = false,
      animation = {
        type = "vertical_frames",
        aspect_w = 16,
        aspect_h = 16,
        length = 2.0,
      },
    },
    {
      name = "basic_water_source_animated.png",
      backface_culling = true,
      animation = {
        type = "vertical_frames",
        aspect_w = 16,
        aspect_h = 16,
        length = 2.0,
      },
    },
  },
  alpha = 191,
  paramtype = "light",
  walkable = false,
  pointable = false,
  diggable = false,
  buildable_to = true,
  is_ground_content = false,
  drop = "",
  drowning = 1,
  liquidtype = "source",
  liquid_alternative_flowing = "basic:water_flowing",
  liquid_alternative_source = "basic:water_source",
  liquid_viscosity = 1,
  post_effect_color = {a = 103, r = 30, g = 60, b = 90},
  groups = {water = 3, liquid = 3, cools_lava = 1},
  sounds = basic.node_sound_water_defaults(),
})

minetest.register_node("basic:water_flowing", {
  description = basic.S("Flowing Water"),
  drawtype = "flowingliquid",
  waving = 3,
  tiles = {"basic_water.png"},
  special_tiles = {
    {
      name = "basic_water_flowing_animated.png",
      backface_culling = false,
      animation = {
        type = "vertical_frames",
        aspect_w = 16,
        aspect_h = 16,
        length = 0.5,
      },
    },
    {
      name = "basic_water_flowing_animated.png",
      backface_culling = true,
      animation = {
        type = "vertical_frames",
        aspect_w = 16,
        aspect_h = 16,
        length = 0.5,
      },
    },
  },
  alpha = 191,
  paramtype = "light",
  paramtype2 = "flowingliquid",
  walkable = false,
  pointable = false,
  diggable = false,
  buildable_to = true,
  is_ground_content = false,
  drop = "",
  drowning = 1,
  liquidtype = "flowing",
  liquid_alternative_flowing = "basic:water_flowing",
  liquid_alternative_source = "basic:water_source",
  liquid_viscosity = 1,
  post_effect_color = {a = 103, r = 30, g = 60, b = 90},
  groups = {water = 3, liquid = 3, not_in_creative_inventory = 1,
    cools_lava = 1},
  sounds = basic.node_sound_water_defaults(),
})
